[package]
name = "app-notify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.17"
ssh2 = "0.9.1"
indicatif = "0.16.2"
chrono= "0.4.19"

[profile.release]
opt-level = 3